name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Usa o secret EXATAMENTE como está no GitHub
        password: ${{ secrets.DOCKER_PASSWORD }}  # Usa o secret EXATAMENTE como está no GitHub

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/api-flask-docker:latest  # Formato: usuario_dockerhub/nome_imagem:tag